from django.contrib.auth import get_user_model
from django.test import TestCase
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APIClient

from .models import Post


class PostModelTests(TestCase):
	def setUp(self):
		self.user = get_user_model().objects.create_user(username='alice', password='testpass123')

	def test_post_slug_autogenerated(self):
		post = Post.objects.create(title='My First Post', content='Content', author=self.user)
		self.assertTrue(post.slug)
		self.assertEqual(post.slug, 'my-first-post')

	def test_post_str_returns_title(self):
		post = Post.objects.create(title='Readable Title', content='Body', author=self.user)
		self.assertEqual(str(post), 'Readable Title')


class PostViewTests(TestCase):
	def setUp(self):
		self.user = get_user_model().objects.create_user(username='author', password='pass12345')
		self.other_user = get_user_model().objects.create_user(username='bob', password='pass12345')
		self.post = Post.objects.create(title='Author Post', content='Body', author=self.user)

	def test_author_can_update_post(self):
		self.client.login(username='author', password='pass12345')
		response = self.client.post(
			reverse('blog:post_update', args=[self.post.slug]),
			{'title': 'Updated Title', 'content': 'New body'},
		)
		self.assertEqual(response.status_code, 302)
		self.post.refresh_from_db()
		self.assertEqual(self.post.title, 'Updated Title')

	def test_non_author_cannot_update_post(self):
		self.client.login(username='bob', password='pass12345')
		response = self.client.post(
			reverse('blog:post_update', args=[self.post.slug]),
			{'title': 'Hacked', 'content': 'Nope'},
		)
		self.assertEqual(response.status_code, 403)
		self.post.refresh_from_db()
		self.assertEqual(self.post.title, 'Author Post')


class PostAPITests(TestCase):
	def setUp(self):
		self.client = APIClient()
		self.user = get_user_model().objects.create_user(username='apiuser', password='api-pass-123')
		self.post = Post.objects.create(title='API Post', content='Body', author=self.user)

	def test_list_posts(self):
		response = self.client.get('/api/posts/')
		self.assertEqual(response.status_code, status.HTTP_200_OK)
		data = response.json()
		self.assertIn('results', data)
		self.assertGreaterEqual(data['count'], 1)

	def test_create_requires_authentication(self):
		response = self.client.post('/api/posts/', {'title': 'New via API', 'content': 'Body'}, format='json')
		self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)
		self.assertEqual(response.json()['detail'], 'Authentication credentials were not provided.')

	def test_authenticated_user_can_create_post(self):
		self.client.login(username='apiuser', password='api-pass-123')
		response = self.client.post('/api/posts/', {'title': 'Created', 'content': 'Body'}, format='json')
		self.assertEqual(response.status_code, status.HTTP_201_CREATED)
		self.assertTrue(Post.objects.filter(title='Created').exists())
